export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE"

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST"
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS"
export const FIND_USER_BY_ID_FAILURE = "FIND_USER_BY_ID_FAILURE"

export const FIND_USER_BY_NAME_REQUEST = "FIND_USER_BY_NAME_REQUEST";
export const FIND_USER_BY_NAME_SUCCESS = "FIND_USER_BY_NAME_SUCCESS";
export const FIND_USER_BY_NAME_FAILURE = "FIND_USER_BY_NAME_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE"

export const GET_UNFOLLOWED_USERS_REQUEST = "GET_UNFOLLOWED_USERS_REQUEST"
export const GET_UNFOLLOWED_USERS_SUCCESS = "GET_UNFOLLOWED_USERS_SUCCESS"
export const GET_UNFOLLOWED_USERS_FAILURE = "GET_UNFOLLOWED_USERS_FAILURE"

export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";

export const MARK_AS_READ_REQUEST = "MARK_AS_READ_REQUEST";
export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_FAILURE = "MARK_AS_READ_FAILURE";

export const MARK_ALL_AS_READ_REQUEST = "MARK_ALL_AS_READ_REQUEST";
export const MARK_ALL_AS_READ_SUCCESS = "MARK_ALL_AS_READ_SUCCESS";
export const MARK_ALL_AS_READ_FAILURE = "MARK_ALL_AS_READ_FAILURE";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAILURE = "CREATE_NOTIFICATION_FAILURE";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

export const DELETE_ALL_NOTIFICATIONS_REQUEST = "DELETE_ALL_NOTIFICATIONS_REQUEST";
export const DELETE_ALL_NOTIFICATIONS_SUCCESS = "DELETE_ALL_NOTIFICATIONS_SUCCESS";
export const DELETE_ALL_NOTIFICATIONS_FAILURE = "DELETE_ALL_NOTIFICATIONS_FAILURE";

// Gửi tin nhắn
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

// Lấy lịch sử chat
export const FETCH_CHAT_HISTORY_REQUEST = "FETCH_CHAT_HISTORY_REQUEST";
export const FETCH_CHAT_HISTORY_SUCCESS = "FETCH_CHAT_HISTORY_SUCCESS";
export const FETCH_CHAT_HISTORY_FAILURE = "FETCH_CHAT_HISTORY_FAILURE";

// Sửa tin nhắn
export const EDIT_MESSAGE_REQUEST = "EDIT_MESSAGE_REQUEST";
export const EDIT_MESSAGE_SUCCESS = "EDIT_MESSAGE_SUCCESS";
export const EDIT_MESSAGE_FAILURE = "EDIT_MESSAGE_FAILURE";

// Xóa tin nhắn
export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILURE = "DELETE_MESSAGE_FAILURE";

// Đánh dấu tin nhắn đã đọc
export const MARK_MESSAGE_AS_READ_REQUEST = "MARK_MESSAGE_AS_READ_REQUEST";
export const MARK_MESSAGE_AS_READ_SUCCESS = "MARK_MESSAGE_AS_READ_SUCCESS";
export const MARK_MESSAGE_AS_READ_FAILURE = "MARK_MESSAGE_AS_READ_FAILURE";

export const RESET_FIND_USER = "RESET_FIND_USER"

export const LOGOUT = "LOGOUT"


